- backend/build.gradle
- backend/src/main/java/edonymyeon/backend/BackendApplication.java
- backend/src/main/java/edonymyeon/backend/controller/PostController.java
- backend/src/main/java/edonymyeon/backend/domain/Post.java
- backend/src/main/java/edonymyeon/backend/domain/exception/EdonymyeonException.java
- backend/src/main/java/edonymyeon/backend/domain/exception/ExceptionCode.java
- backend/src/main/java/edonymyeon/backend/repository/PostRepository.java
- backend/src/main/java/edonymyeon/backend/service/PostService.java
- backend/src/main/java/edonymyeon/backend/service/request/PostRequest.java
- backend/src/main/java/edonymyeon/backend/service/response/PostResponse.java
- backend/src/main/resources/application.properties
- backend/src/test/java/edonymyeon/backend/controller/PostControllerTest.java
- backend/src/test/java/edonymyeon/backend/repository/PostRepositoryTest.java
- backend/src/test/java/edonymyeon/backend/service/PostServiceTest.java
- close: #7 
게시물 작성 기능을 구현하였습니다.
회원 정보과 사진, 오류 발생시 예외 응답은 추후에 구현해야 합니다.
> 몹 프로그래밍을 하면서 놓친 부분을 밝혀내주세요.
> Feat/#7 게시글 작성 기능구현

- backend/src/main/java/edonymyeon/backend/config/WebMvcConfiguration.java
- backend/src/main/java/edonymyeon/backend/controller/PostController.java
- backend/src/main/java/edonymyeon/backend/controlleradvice/GlobalExceptionHandler.java
- backend/src/main/java/edonymyeon/backend/domain/Post.java
- backend/src/main/java/edonymyeon/backend/domain/exception/EdonymyeonException.java
- backend/src/main/java/edonymyeon/backend/domain/exception/ExceptionInformation.java
- backend/src/main/java/edonymyeon/backend/service/AuthenticationService.java
- backend/src/test/java/edonymyeon/backend/controller/PostControllerTest.java
- backend/src/test/resources/dummydata.sql
- close: #24 
게시글 작성 요청이 들어왔을 때, 인증 정보가 없으면 예외가 발생합니다.
> feat: 회원만 게시글을 작성하는 기능 구현

- backend/src/test/java/edonymyeon/backend/support/MemberTestSupport.java
- close: #71 
테스트용 회원 객체를 수정했습니다.
> refactor: 테스트용 회원 객체 기본값 수정

- android/app/src/main/java/com/app/edonymyeon/data/common/CustomThrowable.kt
- android/app/src/main/java/com/app/edonymyeon/data/datasource/post/PostDataSource.kt
- android/app/src/main/java/com/app/edonymyeon/data/datasource/post/PostRemoteDataSource.kt
- android/app/src/main/java/com/app/edonymyeon/data/dto/response/PostDetailResponse.kt
- android/app/src/main/java/com/app/edonymyeon/data/repository/PostRepositoryImpl.kt
- android/app/src/main/java/com/app/edonymyeon/data/service/PostService.kt
- android/app/src/main/java/com/app/edonymyeon/data/service/client/AccessTokenInterceptor.kt
- android/app/src/main/java/com/app/edonymyeon/data/service/client/OkHttpClient.kt
- android/app/src/main/java/com/app/edonymyeon/data/service/client/RetrofitClient.kt
- android/app/src/main/java/com/app/edonymyeon/mapper/PostMapper.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/ui/postdetail/PostDetailActivity.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/ui/postdetail/PostDetailViewModel.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/ui/postdetail/PostDetailViewModelFactory.kt
- android/domain/src/main/java/com/domain/edonymyeon/repository/PostRepository.kt
- close: #63
레트로핏 연결
레트로핏 연결 및 게시글 상세 조회 API 연결
GREAT
> Feat 63 retrofit client

- backend/src/main/resources/application-dev.properties
- backend/src/main/resources/data.sql
- close: #87 
스프링 띄위면 더미 데이터 입력 되도록 하였습니다.
> 스프링 실행시 회원 더미 데이터 추가기능 구현

- backend/src/main/java/edonymyeon/backend/image/domain/Domain.java
- backend/src/main/java/edonymyeon/backend/image/domain/ImageInfo.java
- backend/src/main/java/edonymyeon/backend/post/application/PostService.java
- backend/src/main/java/edonymyeon/backend/post/application/dto/GeneralPostInfoResponse.java
- backend/src/main/java/edonymyeon/backend/post/application/dto/SpecificPostInfoResponse.java
- backend/src/test/java/edonymyeon/backend/post/application/PostServiceFindingAllPostsTest.java
- backend/src/test/java/edonymyeon/backend/post/application/PostServiceTest.java
- backend/src/test/resources/application.properties
- close: #98 
이미지 경로가 null로 나오는 문제를 해결했습니다.
> fix: 이미지 경로가 null로 나오는 문제 해결

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/app/edonymyeon/data/datasource/post/PostDataSource.kt
- android/app/src/main/java/com/app/edonymyeon/data/datasource/post/PostRemoteDataSource.kt
- android/app/src/main/java/com/app/edonymyeon/data/dto/ReactionCountDataModel.kt
- android/app/src/main/java/com/app/edonymyeon/data/dto/WriterNickNameDataModel.kt
- android/app/src/main/java/com/app/edonymyeon/data/dto/response/Post.kt
- android/app/src/main/java/com/app/edonymyeon/data/dto/response/Posts.kt
- android/app/src/main/java/com/app/edonymyeon/data/repository/PostRepositoryImpl.kt
- android/app/src/main/java/com/app/edonymyeon/data/service/PostService.kt
- android/app/src/main/java/com/app/edonymyeon/data/service/client/RetrofitClient.kt
- android/app/src/main/java/com/app/edonymyeon/mapper/PostItemMapper.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/ui/post/PostActivity.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/ui/post/PostDetailViewModelFactory.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/ui/post/PostViewModel.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/ui/post/adapter/PostAdapter.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/ui/post/viewholder/PostViewHolder.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/uimodel/PostItemUiModel.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/util/CustomBindingAdapter.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/util/IntentExtension.kt
- android/app/src/main/res/drawable/btn_back_black.xml
- android/app/src/main/res/drawable/ic_post_filter_open.xml
- android/app/src/main/res/drawable/ic_write_post.xml
- android/app/src/main/res/layout/activity_post.xml
- android/app/src/main/res/layout/item_post.xml
- android/app/src/main/res/values/strings.xml
- android/domain/src/main/java/com/domain/edonymyeon/model/PostItem.kt
- android/domain/src/main/java/com/domain/edonymyeon/repository/PostRepository.kt
> Feat/#10 전체 게시글 목록

- .github/workflows/android-ci-workflow.yml
- close: #140 
Android Unit Test CI 구성
위와 동일합니다 ~
> 다 같이 작성했지요 ~
> feat:#140_Android_Github_actions

- backend/src/main/java/edonymyeon/backend/auth/ui/AuthController.java
- backend/src/test/java/edonymyeon/backend/auth/AuthIntegrationTest.java
- close: #168 
로그인 쿠키를 등록하도록 수정
Authorization 헤더에 Basic 인코딩값을 추가하려고 했는데,
쿠키 값에 공백을 추가할 수 없어서 "Basic " 부분을 빼고 쿠키에 등록하였습니다......
> Fix/#168 로그인 시, 쿠키 등록하도록 수정

- backend/src/main/java/edonymyeon/backend/consumption/application/PostConsumptionServiceImpl.java
- backend/src/test/java/edonymyeon/backend/post/application/MyPostServiceTest.java
- close: #199 
반환 값 잘못되어있는 거 수정
- 반환 값(연,월) 잘못되어 있는거 수정
- 연,월 체크하는 테스트 추가
> Fix/#199 내가 쓴 글 조회 반환 값 수정

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/app/edonymyeon/application/EdonymyeonApplication.kt
- android/app/src/main/java/com/app/edonymyeon/data/datasource/auth/AuthLocalDataSource.kt
- android/app/src/main/java/com/app/edonymyeon/data/datasource/consumptions/ConsumptionsRemoteDataSource.kt
- android/app/src/main/java/com/app/edonymyeon/data/datasource/post/PostRemoteDataSource.kt
- android/app/src/main/java/com/app/edonymyeon/data/datasource/profile/ProfileRemoteDataSource.kt
- android/app/src/main/java/com/app/edonymyeon/data/util/PreferenceUtil.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/MainActivity.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/mypage/MyPageFragment.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/mypage/MyPageViewModel.kt
- android/app/src/main/res/layout/fragment_my_page.xml
- close: #137 
로그인 여부에 따라 뷰와 수행하는 기능들이 달라집니다.
로그인 -> 프로필, 그래프 api 연동, 로그아웃 기능
로그인 X -> 로그인 버튼/기능, 그래프 안보임
> 로그아웃 하면 MainActivity가 재실행되도록 했는데 좋은 방법인지는 모르겠습니다..
> Feat/#137 로그인 여부 뷰

- android/app/src/main/java/com/app/edonymyeon/presentation/ui/posteditor/PostEditorActivity.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/ui/posteditor/PostEditorViewModel.kt
- close: #190 

이미지 용량 quality를 50으로 줄인다.
이미지 bitmap을 압축하는 부분에서 quality를 50으로 줄인다.
> quality를 50으로 줄였습니다!
> refactor: 이미지 용량을 줄인다.

- backend/build.gradle
- backend/src/main/resources/application-prod.properties
- close: #222 
application.properties와 build.gradle에 프로메테우스(메트릭 데이터를 수집하는 도구) 관련 설정을 추가하였습니다.
> chore: 모니터링을 위한 프로메테우스 설정 추가

- backend/src/main/resources/application-prod.properties
- close: #241 
없어도 되는 설정을 제거했읍니다.
> refactor: 없어도 되는 설정 제거

- android/app/build.gradle.kts
- android/app/src/main/AndroidManifest.xml
- android/build.gradle.kts
- close: #188
firebase crashlytics 추가
> feat: firebase crashlytics 추가

- backend/src/main/java/edonymyeon/backend/global/exception/ExceptionInformation.java
- backend/src/main/java/edonymyeon/backend/logging/LoggingInterceptor.java
- backend/src/main/java/edonymyeon/backend/report/application/ReportRepository.java
- backend/src/main/java/edonymyeon/backend/report/application/ReportRequest.java
- backend/src/main/java/edonymyeon/backend/report/application/ReportService.java
- backend/src/main/java/edonymyeon/backend/report/domain/AbusingType.java
- backend/src/main/java/edonymyeon/backend/report/domain/Report.java
- backend/src/main/java/edonymyeon/backend/report/ui/ReportController.java
- backend/src/test/java/edonymyeon/backend/IntegrationTest.java
- backend/src/test/java/edonymyeon/backend/post/integration/PostIntegrationTest.java
- backend/src/test/java/edonymyeon/backend/post/integration/PostViewIntegrationTest.java
- backend/src/test/java/edonymyeon/backend/report/ReportServiceTest.java
- backend/src/test/java/edonymyeon/backend/report/ui/ReportIntegrationTest.java
- backend/src/test/java/edonymyeon/backend/support/PostIntegrationTestSupport.java
- close: #240 
특정 게시글을 신고하는 기능을 추가합니다.
> Feat/#240 신고하기 API 🚨

- android/app/build.gradle.kts
- android/app/src/main/java/com/app/edonymyeon/data/datasource/report/ReportDataSource.kt
- android/app/src/main/java/com/app/edonymyeon/data/datasource/report/ReportRemoteDataSource.kt
- android/app/src/main/java/com/app/edonymyeon/data/dto/request/ReportRequest.kt
- android/app/src/main/java/com/app/edonymyeon/data/repository/ReportRepositoryImpl.kt
- android/app/src/main/java/com/app/edonymyeon/data/service/ReportService.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/ui/postdetail/PostDetailActivity.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/ui/postdetail/PostDetailViewModel.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/ui/postdetail/PostDetailViewModelFactory.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/ui/postdetail/dialog/ReportDialog.kt
- android/app/src/main/res/layout/dialog_report.xml
- android/app/src/main/res/menu/menu_post_detail.xml
- android/app/src/main/res/values/strings.xml
- android/app/src/test/java/com/app/edonymyeon/presentation/ui/postdetail/PostDetailViewModelTest.kt
- android/domain/src/main/java/com/domain/edonymyeon/repository/ReportRepository.kt
- close: #239 
신고하기 기능 추가했습니다.
> Feat/#239 신고하기 기능추가

- android/app/src/main/java/com/app/edonymyeon/presentation/ui/post/PostActivity.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/ui/posteditor/PostEditorActivity.kt
- close: #234 
게시글 목록 화면에서 글 세부화면 갔다올시 재조회 버그 수정
ActivityForResult로 해결했습니다~!
코드 간단해서 금방 확인 될 것 같습니다~!
> fix: 재조회 버그 수정

- android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/search/SearchFragment.kt
- close: #232 
EditText 클릭해도 검색 키보드가 뜨게 수정
focus를 주고 검색 상태로 설정주는 방식으로 했습니다. 
다른 좋은 방법이 있을까요..?!
> feat: EditText를 클릭해도 검색 가능하게 수정

- android/app/src/main/java/com/app/edonymyeon/mapper/PostItemMapper.kt
- android/app/src/main/java/com/app/edonymyeon/mapper/PostMapper.kt
- android/app/src/main/java/com/app/edonymyeon/mapper/ReactionMapper.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/common/customview/PostReactionView.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/home/HomeViewModel.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/home/viewholder/HotPostViewHolder.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/ui/post/viewholder/PostViewHolder.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/ui/postdetail/PostDetailActivity.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/ui/postdetail/PostDetailViewModel.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/uimodel/ReactionCountUiModel.kt
- android/app/src/main/res/layout/activity_post.xml
- android/app/src/main/res/layout/activity_post_detail.xml
- android/app/src/main/res/layout/activity_post_editor.xml
- android/app/src/main/res/layout/view_post_reaction.xml
- android/app/src/main/res/values/strings.xml
- android/app/src/test/java/com/app/edonymyeon/presentation/ui/main/home/HomeViewModelTest.kt
- android/app/src/test/java/com/app/edonymyeon/presentation/ui/postdetail/PostDetailViewModelTest.kt
- android/domain/src/main/java/com/domain/edonymyeon/model/ReactionCount.kt
- close: #271 #212 #210 
필요없는 기능들을 삭제했습니다.
정렬, 스크랩 관련 뷰 및 기능 로직들을 삭제했습니다.
> 추가적으로 덜 제거된 사항들이 있는지, 제거된 기능에 따라 혹시나 잘 되지 않는 기능이 혹여 남았는지, 이 두 가지를 봐주시면 좋을 것 같아요!
> Refactor/#271 필요없는 로직 삭제

- backend/src/main/resources/application-dev.properties
- backend/src/main/resources/application-prod.properties
- backend/src/test/resources/application.properties
- close: #301 
이전 이슈 #290 에서 지우길 까먹은 주석을 삭제하였습니다.
> refactor: properties 파일 주석 제거

- android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/home/HomeFragment.kt
- android/app/src/main/res/layout/fragment_home.xml
- android/app/src/main/res/values/strings.xml
- close: #312 
핫 게시글이 없는 경우 뷰 처리
핫 게시글이 없는 경우 이번 주는 핫게시글이 없음을 알려주도록 하였습니다.
수정 사항이 많지는 않아서 빠르게 확인 가능할 것 같아요!
> Refactor/#312_핫 게시글이 없는 경우 뷰 처리

- android/app/src/main/java/com/app/edonymyeon/mapper/PostItemMapper.kt
- android/app/src/main/java/com/app/edonymyeon/mapper/WriterMapper.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/mypage/MyPageFragment.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/mypage/MyPageViewModel.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/ui/mypost/MyPostActivity.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/ui/post/PostActivity.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/ui/postdetail/PostDetailActivity.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/ui/posteditor/PostEditorActivity.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/uimodel/AllPostItemUiModel.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/uimodel/NicknameUiModel.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/uimodel/PostItemUiModel.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/uimodel/WriterUiModel.kt
- android/app/src/main/res/layout/activity_post_detail.xml
- android/app/src/main/res/layout/dialog_input_consumption.xml
- android/app/src/main/res/layout/fragment_my_page.xml
- android/app/src/main/res/values/strings.xml
- close: #329 
글 작성한 후 상세페이지로 이동하기 및 카톡 닉네임 및 다이얼로그 문구 수정
> Feat/#329 글작성후 상세페이지로

- backend/src/main/java/edonymyeon/backend/auth/application/AuthService.java
- backend/src/main/java/edonymyeon/backend/auth/application/dto/LogoutRequest.java
- backend/src/main/java/edonymyeon/backend/auth/application/event/LogoutEvent.java
- backend/src/main/java/edonymyeon/backend/auth/ui/AuthController.java
- backend/src/main/java/edonymyeon/backend/global/exception/ExceptionInformation.java
- backend/src/main/java/edonymyeon/backend/member/application/DeviceRepository.java
- backend/src/main/java/edonymyeon/backend/member/application/MemberEventListener.java
- backend/src/main/java/edonymyeon/backend/member/application/MemberService.java
- backend/src/main/java/edonymyeon/backend/notification/infrastructure/FCMNotificationSender.java
- backend/src/test/java/edonymyeon/backend/auth/application/AuthServiceTest.java
- close: #327 
수동으로 로그아웃한 디바이스의 디바이스 토큰을 deactivate하여
더이상 알림이 전송되지 않게 합니다.
> feat: 로그아웃한 디바이스의 디바이스 토큰을 비활성화하는 기능 추가

- backend/src/main/java/edonymyeon/backend/auth/application/AuthService.java
- backend/src/main/java/edonymyeon/backend/auth/application/dto/LogoutRequest.java
- backend/src/main/java/edonymyeon/backend/auth/application/event/LogoutEvent.java
- backend/src/main/java/edonymyeon/backend/auth/ui/AuthController.java
- backend/src/main/java/edonymyeon/backend/global/exception/ExceptionInformation.java
- backend/src/main/java/edonymyeon/backend/member/application/DeviceRepository.java
- backend/src/main/java/edonymyeon/backend/member/application/MemberEventListener.java
- backend/src/main/java/edonymyeon/backend/member/application/MemberService.java
- backend/src/main/java/edonymyeon/backend/notification/application/dto/Data.java
- backend/src/main/java/edonymyeon/backend/notification/infrastructure/FCMNotificationSender.java
- backend/src/test/java/edonymyeon/backend/auth/application/AuthServiceTest.java
> hotfix/FCM 에러 해결

- backend/src/test/java/edonymyeon/backend/post/integration/PostCommentCountIntegrationTest.java
> fix: 핫 게시글 조회 정책 변경으로 인한 깨지는 테스트 수정

- backend/src/main/java/edonymyeon/backend/post/application/dto/response/MyPostResponse.java
- backend/src/test/java/edonymyeon/backend/member/integration/MemberIntegrationTest.java
- backend/src/test/java/edonymyeon/backend/post/integration/MyPostIntegrationTest.java
- backend/src/test/java/edonymyeon/backend/post/integration/PostCommentCountIntegrationTest.java
- backend/src/test/java/edonymyeon/backend/support/IntegrationFixture.java
- close: #425 
내가 쓴 글 조회에서 댓글수가 제대로 조회 안되는 버그를 수정하고,테스트를 추가했습니다.
> fix: 내가 쓴 글 조회에서 댓글수가 제대로 조회 안되는 버그 수정

- android/app/src/main/java/com/app/edonymyeon/data/dto/NotificationDataModel.kt
- android/app/src/main/java/com/app/edonymyeon/mapper/NotificationMapper.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/alarm/AlarmFragment.kt
- close: #437 
수행한 작업을 1~2줄 사이로 요약해주세요.
> Fix:437_alarm bug

- android/app/src/main/java/com/app/edonymyeon/data/repository/AuthRepositoryImpl.kt
- android/app/src/main/java/com/app/edonymyeon/data/service/client/AccessTokenInterceptor.kt
- close: #436 
수행한 작업을 1~2줄 사이로 요약해주세요.
> feat: 헤더 이름 세션에 맞게 수정

- backend/src/main/java/edonymyeon/backend/post/application/PostService.java
- backend/src/test/java/edonymyeon/backend/post/application/PostServiceTest.java
- close: #450 
게시글 수정시 early-return을 빠뜨린 것을 수정하였습니다
> fix: 게시글 수정시 npe 해결

- android/app/build.gradle.kts
- android/app/src/main/java/com/app/edonymyeon/data/service/client/AccessTokenInterceptor.kt
- close: #448 
header에 버저닝을 적용시켜줬습니다!
고민인 점은 header에 일단 버저닝 적용을 위해서 X-API-VERSION=1을 값을 넣어주고 있습니다. BuildConfig를 통해 버전을 가져올 수 있는데 지금 버전이 "2.0.0"으로 되어 있어서 이 버전을 바꾸고 이 값을 가져오는게 맞을지 "1"을 우선 넣어주는게 맞는지 고민이 되네요!!
> feat: header에 버저닝 적용

- backend/src/main/java/edonymyeon/backend/auth/application/AuthService.java
- backend/src/main/java/edonymyeon/backend/auth/ui/AuthController.java
- backend/src/main/java/edonymyeon/backend/member/domain/Member.java
- backend/src/test/java/edonymyeon/backend/member/domain/MemberTest.java
- close: #457 
회원 정보 암호화에 사용한 코드들 삭제했습니다(todo)
> fix: 회원 정보 암호화시 사용한 코드들 삭제

- android/app/src/main/java/com/app/edonymyeon/data/service/client/AccessTokenInterceptor.kt
- close: #496 
어플 버전에 맞게 api header에 전달하도록 하였습니다!!
어플 버전에 맞게 BuildCofig에서 version name을 가져와서 넣어주도록 하였습니다.
매우 간단해서 1분도 안 걸립니다!!
> refactor/#496_어플 버전에 맞게 api에 전달하도록 수정

- android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/mypage/MyPageFragment.kt
- android/app/src/main/res/layout/fragment_my_page.xml
- android/app/src/main/res/values/strings.xml
- close: #494 
문의하기를 누르면 구글 폼 링크로 이동해요
> very simple super easy
> Feat/#494 문의하기

- android/app/src/main/java/com/app/edonymyeon/presentation/ui/posteditor/PostEditorActivity.kt
- android/app/src/main/java/com/app/edonymyeon/presentation/ui/posteditor/PostEditorViewModel.kt
- android/app/src/main/res/values/strings.xml
- close: #507 
수행한 작업을 1~2줄 사이로 요약해주세요.
> fix: 금액 미 입력시 등록이 되지 않도록 수정

- .github/workflows/android-ci-workflow.yml
- android/app/build.gradle.kts
- android/domain/src/main/java/com/domain/edonymyeon/model/Email.kt
- close: #515 
수행한 작업을 1~2줄 사이로 요약해주세요.
> 안드로이드 CD 개선 희망
