woowacourse-teams/2023-edonymyeon

android/app/build.gradle.kts, android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/MainActivity.kt, android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/MainAdapter.kt, android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/alarm/AlarmFragment.kt, android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/category/CategoryFragment.kt, android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/home/HomeFragment.kt, android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/mypage/MyPageFragment.kt, android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/search/SearchFragment.kt, android/app/src/main/res/drawable/ic_bottom_nav_alarm.xml, android/app/src/main/res/drawable/ic_bottom_nav_category.xml, android/app/src/main/res/drawable/ic_bottom_nav_home.xml, android/app/src/main/res/drawable/ic_bottom_nav_my_page.xml, android/app/src/main/res/drawable/ic_bottom_nav_search.xml, android/app/src/main/res/drawable/selector_bottom_nav_icon_tint.xml, android/app/src/main/res/layout/activity_main.xml, android/app/src/main/res/layout/fragment_alarm.xml, android/app/src/main/res/layout/fragment_category.xml, android/app/src/main/res/layout/fragment_home.xml, android/app/src/main/res/layout/fragment_my_page.xml, android/app/src/main/res/layout/fragment_preparing_page.xml, android/app/src/main/res/layout/fragment_search.xml, android/app/src/main/res/menu/bottom_menu.xml, android/app/src/main/res/values/colors.xml, android/app/src/main/res/values/strings.xml
- close: #6
바텀 네비게이션 구현 및 프레그먼트 연결
바텀 네비게이션을 show/hide 방식으로 구현, 2차 데모데이 때 발표할 프레그먼트 외에 준비 중인 페이지 TextView를 출력하도록 함
build.gradle에 fragment-ktx 추가(commit 등 프레그먼트 트랜젝션 명령어를 간단하게 사용가능)
MainActivity 위주로 봐주시면 좋을 것 같습니다:) ViewModel등 라이브러리를 활용한 더 좋은 방안도 있을까요..?
=> Feat/#6 메인 페이지

backend/src/main/java/edonymyeon/backend/controller/AuthController.java, backend/src/main/java/edonymyeon/backend/domain/Member.java, backend/src/main/java/edonymyeon/backend/domain/exception/ExceptionCode.java, backend/src/main/java/edonymyeon/backend/repository/MemberRepository.java, backend/src/main/java/edonymyeon/backend/service/AuthenticationService.java, backend/src/main/java/edonymyeon/backend/service/request/LoginRequest.java, backend/src/main/java/edonymyeon/backend/service/response/MemberIdDto.java
- close: #5 
로그인 기능 구현
로그인 시, 사용자의 이메일과 비밀번호를 받는다.
해당하는 사용자가 있는지 확인한다.
사용자 정보로 Basic 인증정보를 쿠키에 담는다.
=> feat: Member 로그인 기능 구현

backend/src/main/java/edonymyeon/backend/global/exception/ExceptionInformation.java, backend/src/main/java/edonymyeon/backend/member/domain/Member.java, backend/src/main/java/edonymyeon/backend/post/application/PostService.java, backend/src/main/java/edonymyeon/backend/post/domain/Post.java, backend/src/main/java/edonymyeon/backend/post/ui/PostController.java, backend/src/test/java/edonymyeon/backend/repository/PostRepositoryTest.java, backend/src/test/java/edonymyeon/backend/service/PostServiceTest.java, backend/src/test/resources/dummydata.sql
- close: #55 
게시글 작성 요청 시에 들어오는 회원 정보(Member)를 게시글(Post)에 저장하여 게시글의 작성자가 누구인지 알 수 있게 구현
서비스에서 Dto를 통해 들어오는 회원 id를 이용해 회원 정보를 조회
- `서비스에서 서비스를 참조하는 구조`(PostService에서 회원 id로 member를 가져오기 위해 MemberService를 이용)를 아직 서비스가 미완성된 상태라 사용할 수 없어서, 일단 PostService에서 MemberRepository를 통해 member를 가져오도록 하였습니다. 
- ExceptionInformation에 enum 추가하였습니다.
Post - Member 관계를 `@ManyToOne으로 설정`
- 그렇습니다.
깨지는 테스트 코드 수정
- 테스트용 ddl 파일 및 깨지는 테스트 코드를 수정하였습니다.
> Dto에 @NotNull을 붙여주는 것이 어떨까요?! 서비스에서 MemberIdDto 값이 null인 것을 검증하는 로직을 넣으려다가 남겨두었습니다.
=> feat/#55 게시글에 작성자 정보를 저장하는 기능 구현

backend/src/main/java/edonymyeon/backend/global/exception/ExceptionInformation.java, backend/src/main/java/edonymyeon/backend/thumbs/application/ThumbsService.java, backend/src/main/java/edonymyeon/backend/thumbs/domain/Thumbs.java, backend/src/main/java/edonymyeon/backend/thumbs/domain/ThumbsType.java, backend/src/main/java/edonymyeon/backend/thumbs/repository/ThumbsRepository.java, backend/src/main/java/edonymyeon/backend/thumbs/ui/ThumbsController.java, backend/src/test/java/edonymyeon/backend/thumbs/application/ThumbsServiceTest.java, backend/src/test/java/edonymyeon/backend/thumbs/integration/ThumbsUpIntegrationTest.java
- close: #13 
게시글 추천 기능을 작성하고 테스트를 추가하였습니다.
현재 모든 테스트/ postman 요청 성공합니다.
- 로그인 되어있을때에만 게시글 추천이 가능합니다.
- 아이디에 해당하는 게시글이 있을때에만 추천이 가능합니다.
- 해당 게시글이 다른 사람이 작성한 글일때만 추천이 가능합니다.
- 이전에 추천/ 비추천한 내역이 없을시 새롭게 추가됩니다.
- 이전에 비추천한 내역이 있을시 추천으로 변경됩니다.
- 이전에 추천한 내역이 있을시 오류가 발생합니다 (추천 취소는 다른 api로 진행됨)
컨벤션에서 주요 로직을 도메인에서 처리하기로 했던것 같은데, 
추천 도메인 성격상 서비스에 때려 넣게 됩니다.....
좋은 수정 아이디어가 있다면 추천 부탁 드립니다 ㅎㅎ
컨벤션에서 주요 로직을 도메인에서 처리하기로 했던것 같은데, 
추천 도메인 성격상 서비스에 때려 넣게 됩니다.....
좋은 수정 아이디어가 있다면 추천 부탁 드립니다 ㅎㅎ
서비스 테스트에서 추천 서비스와 레포지토리를 동시에 필드에 두고 테스트 하는 방법도 괜찮나여??
해당 요청의 응답은 status만 필요하고, 서비스에서 사용자 id와 post id로 추천 1개를 읽어오는 일은 업을 것 같아서 일케 구현 햇읍니다...
첫 리뷰 요청 잘부탁드립니다 !!!!! 🐸
=> feat/#13 게시글 추천 기능구현 

backend/src/main/java/edonymyeon/backend/member/domain/Member.java, backend/src/test/java/edonymyeon/backend/member/domain/MemberTest.java
- close: #69 
- 닉네임 제한을 20자 까지로 수정하였습니다.
=> refactor: 닉네임 제한 20자까지로 수정

backend/src/main/java/edonymyeon/backend/post/application/PostService.java
- close: #76 
게시글 작성시 사진 없는데 디렉터리에 파일 생성되는 버그를 수정하였습니다.
안드로이드쪽에 확인을 해보니, 게시글 작성 요청이 들어올때 이미지가 있든 없든 images 필드가 꼭 들어와야하는데, 포스트맨에서 images 필드를 선택하고 아무런 이미지를 첨부하지 않으니, 저희의 PostService에 있는 images null확인 및 isEmpty() 검증 로직에 걸리지 않는 것을 발견하였습니다.
images.get(0).isEmpty()까지 체크를 해야 비어있는 멀티파일 리스트임을 확인 가능해서 해당 방향으로 수정하였습니다.
> ㅜㅜ
=> Fix/#76 게시글 작성시 사진 없는데 디렉터리에 파일 생성되는 버그 수정

backend/src/main/java/edonymyeon/backend/post/application/PostService.java, backend/src/test/java/edonymyeon/backend/post/application/PostServiceTest.java
- close: #96 
작성자의 프로필 사진이 없더라도 NPE가 발생하지 않도록 버그를 수정했습니다.
=> fix: 작성자의 프로필 사진이 없더라도 NPE가 발생하지 않도록 버그 수정

backend/src/main/java/edonymyeon/backend/post/application/PostService.java, backend/src/main/java/edonymyeon/backend/thumbs/application/ThumbsService.java, backend/src/main/java/edonymyeon/backend/thumbs/repository/ThumbsRepository.java
게시글과 추천의 연관관계 때문에 게시글이 삭제가 되지 않는 오류 수정
=> fix: 게시글과 추천의 연관관계 때문에 게시글이 삭제가 되지 않는 오류 수정

backend/src/main/java/edonymyeon/backend/global/exception/ExceptionInformation.java, backend/src/main/java/edonymyeon/backend/image/ImageFileUploader.java, backend/src/main/java/edonymyeon/backend/image/postimage/domain/PostImageInfos.java, backend/src/main/java/edonymyeon/backend/post/application/PostService.java, backend/src/main/java/edonymyeon/backend/post/domain/Post.java, backend/src/test/java/edonymyeon/backend/post/ImageFileCleaner.java, backend/src/test/java/edonymyeon/backend/post/application/PostServiceFindingAllPostsTest.java, backend/src/test/java/edonymyeon/backend/post/application/PostServiceTest.java, backend/src/test/java/edonymyeon/backend/post/integration/PostIntegrationTest.java, backend/src/test/java/edonymyeon/backend/post/ui/PostControllerTest.java
- close: #106 
- 게시글 등록, 수정 시 이미지 10개 검증 로직을 추가
- 테스트할때 이미지가 생성되어 저장되는 테스트 클래스들에 `@AfterEach`로 테스트가 끝난 후 해당 디렉토리의 이미지 파일들을 삭제하는 테스트 추가
게시글 등록, 수정 시 이미지 10개 검증 로직을 추가
- 이미지 개수 검증의 위치를 최대한 도메인으로 집어넣고 싶었으나, 이미지 파일이 생성되어 디렉토리에 저장되기 전에 이미지 개수 검증을 하기 위해 적당히 서비스와 타협하였습니다. 😭 그래서 현재 서비스에서 Post 클래스의 isValidImageNumber 메서드를 호출해서 이미지 개수를 검증하고 있습니다만, 좋은 의견 있으시면 코멘투 주세요 ~! 적극 반영해보겠습니다~
- 관련 테스트 코드를 추가했습니다. (PostServiceTest)
테스트할때 이미지가 생성되어 저장되는 테스트 클래스들에 `@AfterEach`로 테스트가 끝난 후 해당 디렉토리의 이미지 파일들을 삭제하는 테스트 추가
- Post 관련 테스트들 중, 이미지를 생성하는 테스트 클래스들에게 테스트가 끝난 후 이미지 파일 지우는 코드를 추가했습니다.
=> Feat/#106 게시글 작성, 수정할 때 개수 제한 및 테스트 후 이미지 삭제 기능 구현

backend/build.gradle, backend/src/main/resources/application-prod.properties
- close: #165 
* 운영 환경(prod) 에서는 ec2에 설치된 mySQL 데이터베이스를 사용합니다.
* 운영 데이터베이스가 내려가지 않도록 ddl-auto 설정을 삭제했습니다.
* 데이터베이스 주소, username과 password는 ec2 내부의 환경변수를 사용하고, 애플리케이션은 해당 환경변수를 사용하도록 하여 내부정보 유출을 방지합니다.
=> feat: prod 환경에서 mysql을 사용하도록 설정

backend/src/main/java/edonymyeon/backend/auth/application/AuthService.java, backend/src/main/java/edonymyeon/backend/global/exception/ExceptionInformation.java, backend/src/main/java/edonymyeon/backend/member/domain/Member.java, backend/src/main/java/edonymyeon/backend/member/repository/MemberRepository.java, backend/src/main/resources/application-prod.properties
- close: #176 
- 로그인 로직을 수정하였습니다.
- 배포환경에서 더미 데이터가 추가되지 않도록 수정하였습니다.
- 기존 DB에서 아이디, 비밀번호로 조회하던 걸, 아이디로 가져와서 회원 객체에서 비밀번호 검증을 하도록 수정하였습니다.
=> Refactor/#176 로그인 로직 수정

backend/src/main/java/edonymyeon/backend/global/logging/LoggingFilter.java, backend/src/main/java/edonymyeon/backend/global/logging/LoggingInterceptor.java
- close: #179 
인터셉터 진입 전에 예외가 터졌을 시 예외응답이 반환되지 않는 버그를 수정하였습니다.
=> fix: 인터셉터 진입 전에 예외가 터졌을 시 예외응답이 반환되지 않는 버그 수정

backend/src/main/java/edonymyeon/backend/member/application/MemberService.java
- close: #182 
MemberService에 `@Transactional` 어노테이션을 빠뜨려 `@Transactional(readOnly=true)`가 적용되는 부분을 수정하였습니다
=> fix: transactional 어노테이션 빠뜨린 것 추가

backend/src/main/java/edonymyeon/backend/global/exception/ExceptionInformation.java, backend/src/main/java/edonymyeon/backend/post/domain/Post.java, backend/src/test/java/edonymyeon/backend/post/integration/PostIntegrationTest.java
- close: #184 
안드로이드에서 null값이 "null" 문자열로 보내는 이슈가 있어, ""로 대신해 보내는 전략으로 변경하였습니다.
이에따라 백엔드에서는 게시글 등록 조건에서, 내용 글자수 제한을 0자 이상으로 완화하였습니다.
=> refactor: 게시글 등록 조건 수정

backend/src/main/java/edonymyeon/backend/global/controlleradvice/GlobalExceptionHandler.java, backend/src/main/java/edonymyeon/backend/global/exception/ExceptionInformation.java, backend/src/test/java/edonymyeon/backend/image/ImageFileSizeIntegrationTest.java, backend/src/test/java/edonymyeon/backend/post/integration/PostImageFileSizeIntegrationTest.java, backend/src/test/resources/application.properties
- close: #174 
파일 하나의 크기가 20MB를 초과할 경우, 요청 전체의 크기가 200MB를 초과할 경우의 예외를 잡아 처리하는 기능을 ExceptionHandler에 추가하였습니다.
테스트 코드로 테스트한 상황은 아래 세가지 상황을 테스트 하였습니다.
- 20 MB 이하의 파일 전송
- 20 MB 초과의 파일 전송
- 200 MB 이하의 요청 전송
200 MB 초과의 요청 전송은 테스트 코드가 실행되다가 요청이 닫혀버리며 예외가 발생하기에, (java.net.socketexception: broken pipe)
대신 로컬 환경에서 포스트맨 상으로 정상 동작이 되는 것을 확인하였습니다.
=> feat: 파일 용량 제한을 초과하는 파일이 들어온 경우 예외처리 기능 추가

android/app/src/main/AndroidManifest.xml
- close: #233 
EditText가 보이게 수정하였습니다.
manifest 설정으로 키보드 위로 밀리게 수정했어요!
테스트만 해봐도 될 것 같습니다
=> fix: 키보드가 EditText를 가리는 버그 수정

backend/src/docs/asciidoc/common/post-api.adoc, backend/src/main/java/edonymyeon/backend/global/config/WebMvcConfiguration.java, backend/src/main/java/edonymyeon/backend/post/application/GeneralFindingCondition.java, backend/src/main/java/edonymyeon/backend/post/application/HotFindingCondition.java, backend/src/main/java/edonymyeon/backend/post/application/PostReadService.java, backend/src/main/java/edonymyeon/backend/post/domain/HotPostPolicy.java, backend/src/main/java/edonymyeon/backend/post/repository/PostRepository.java, backend/src/main/java/edonymyeon/backend/post/ui/PostReadController.java, backend/src/main/java/edonymyeon/backend/post/ui/annotation/HotPostSizing.java, backend/src/main/java/edonymyeon/backend/post/ui/annotation/PostPaging.java, backend/src/main/java/edonymyeon/backend/post/ui/argumentresolver/HotPostSizingArgumentResolver.java, backend/src/test/java/edonymyeon/backend/post/docs/PostControllerDocsTest.java, backend/src/test/java/edonymyeon/backend/post/integration/HotPostIntegrationTest.java, backend/src/test/java/edonymyeon/backend/post/repository/PostRepositoryTest.java, backend/src/test/java/edonymyeon/backend/report/ReportServiceTest.java, backend/src/test/java/edonymyeon/backend/support/ThumbsUpPostTestSupport.java
- close: #225 
핫게시글 정책에 따라 핫게시글을 구해온다 
핫 게시글에 대한 기능구현중 가장 첫번째 기능인 
정책에 따라서 핫 게시글을 조회해오는 부분 입니다.
지금은 요청을 보내면 바로 핫게시글을 구해서 응답하는 식으로 구현했지만
캐싱과 스케줄러를 이용하여 30분마다 구하여 캐싱하는 방법으로 바꿀 예정입니다 !
지금은 정책에 따라 핫 게시글을 구하는 로직을 위주로 봐주세여 ><
현재 핫 게시글 정책은
- 최근 7일 이내의 글
- 좋아요 * 3
- 조회수 * 1
인데요 이를 어떻게 관리하면 좋을지 고민하다가...
일단는 상수들만 모아놓은 HotPostPolicy클래스를 만들어 가독성이 나아지도록 만들었는데용!
더 좋은 방법이 있다면 공유 부탁드림미다.... (또 현재 도메인 패키지에 넣어두었는데 이부분도 화긴점여..)
또 핫 게시글을 조회하는 개수 또한 정책에 따라 자주 바뀔 수 있다고 판단되어 전체 게시글 조회와 비슷하게
size와 page를 쿼리 파라미터로 클라이언트로부터 받도록 하였습니다 !
핫 게시글의 기본 사항들을 전체 게시글 조회랑은 조금 달라서 @HotSizing 이라는 어노테이션을 새로 만들었습니당 ㅎㅅㅎ
=> Feat: 핫 게시글을 정책에 따라 조회하는 기능 구현

backend/src/main/java/edonymyeon/backend/cache/application/BooleanTemplate.java, backend/src/main/java/edonymyeon/backend/cache/application/LongTemplate.java, backend/src/main/java/edonymyeon/backend/cache/application/PostCachingService.java, backend/src/main/java/edonymyeon/backend/cache/util/CacheKeyStrategy.java, backend/src/main/java/edonymyeon/backend/cache/util/HotPostCachePolicy.java, backend/src/main/java/edonymyeon/backend/cache/util/ProductCacheKeyStrategy.java, backend/src/test/java/edonymyeon/backend/post/application/PostServiceHotPostsTest.java, backend/src/test/java/edonymyeon/backend/post/application/TestCacheKeyStrategy.java
- close: #289 
기존에 스프링 스케줄러로 캐싱을 비우려 하였으나 스프링 스케줄러는 멀티 스레드 환경에서 여러번 동작할 수 있다는 것을 알았습니다 ! 
레디스 캐싱값은 여러번 비워질 필요가 없었기 때문에 스케줄러로 진행하지 않았습니다 
대신 캐싱값을 저장할때 유효 기간을 두어 시간이 지남에 따라 자동으로 소멸 되도록 만들었습니다 !
큰 변경은 없으니 간단하게 확인 부탁 드려용 ㅎㅎ
=> feat: 핫게시글 정보를 캐싱할때 expire 기간을 두어서 30분마다 캐시가 비워지도록 한다

android/app/src/main/java/com/app/edonymyeon/presentation/ui/mypost/MyPostActivity.kt, android/app/src/main/java/com/app/edonymyeon/presentation/ui/mypost/MyPostViewModel.kt, android/app/src/main/java/com/app/edonymyeon/presentation/ui/mypost/MyPostViewModelFactory.kt, android/app/src/main/java/com/app/edonymyeon/presentation/ui/mypost/dialog/ConsumptionDialog.kt, android/app/src/test/java/com/app/edonymyeon/presentation/ui/mypost/MyPostViewModelTest.kt
- close: #295 
구매 확정 다이얼로그에 원래 금액이 먼저 보이도록 수정
원래 구매 확정 다이얼로그를 열면 금액 입력 받는 부분이 빈칸으로 되어 있는데 자신이 썼던 글에 저장된 금액이 보여지는게 좋을 것 같아서
수정하였습니다!
고친 부분이 많지 않아서 리뷰는 오래 걸리지 않을 것 같아요!😄
=> Refactor/#295_구매 확정 다이얼로그에 원래 금액이 먼저 보이도록 수정

backend/src/main/java/edonymyeon/backend/consumption/application/PostConsumptionServiceImpl.java, backend/src/main/java/edonymyeon/backend/consumption/domain/Consumption.java, backend/src/main/java/edonymyeon/backend/consumption/repository/ConsumptionRepository.java, backend/src/main/java/edonymyeon/backend/post/application/PostConsumptionService.java, backend/src/main/java/edonymyeon/backend/post/application/PostService.java, backend/src/main/java/edonymyeon/backend/thumbs/application/event/PostDeletionEvent.java, backend/src/test/java/edonymyeon/backend/post/application/PostServiceTest.java
- close: #293 
게시글 삭제시 on delete cascade 대신 레포지토리를 통해 소비내역을 삭제하도록 수정하였습니다.
(merge가 되면) 이후 데이터베이스에 직접 접속하여 다음 쿼리로 포린키 이름을 조회 후,
```
select * from information_schema.table_constraints where table_name = 'consumption';
```
다음 쿼리를 실행할 예정입니다.
```
alter table consumption drop foreign key 포린키이름;
alter table consumption add constraint foreign key (post_id) references post (id);
```
=> refactor: 게시글 삭제시 on delete cascade 대신 레포지토리를 통해 소비내역을 삭제하도록 수정

backend/src/main/resources/console-error-appender.xml, backend/src/main/resources/console-info-appender.xml, backend/src/main/resources/console-warn-appender.xml
- close: #305 
기존에 backend 하위에 생성되었던 로그 히스토리들이 킹받아서
로그 히스토리 파일들의 저장 경로를 logs 폴더 하위로 수정하였습니다.
=> refactor: 로그파일 저장 경로 수정

backend/src/main/java/edonymyeon/backend/cache/application/PostCachingService.java, backend/src/main/java/edonymyeon/backend/cache/application/dto/CachedPostResponse.java, backend/src/main/java/edonymyeon/backend/post/application/PostReadService.java, backend/src/test/java/edonymyeon/backend/post/application/PostServiceHotPostsTest.java
- close: #311 
현재 캐싱된 핫게시글이 5개일 때 핫 게시글을 삭제하면, 4개만 조회된다!
캐싱된 개수와 실제 조회개수가 달라지면 캐싱 값을 업데이트 하도록 한다
=> Fix/#311 캐싱된 게시글이 삭제된 경우 처리

backend/src/main/java/edonymyeon/backend/auth/application/AuthService.java, backend/src/main/java/edonymyeon/backend/auth/ui/AuthController.java, backend/src/main/java/edonymyeon/backend/auth/ui/argumentresolver/AuthArgumentResolver.java, backend/src/test/java/edonymyeon/backend/auth/application/AuthDeleteServiceTest.java, backend/src/test/java/edonymyeon/backend/auth/docs/AuthControllerDocsTest.java
- close: #325 
- 카카오톡 로그인 한 유저가 회원 탈퇴 후, 로그인 시 로직 추가
- 로그인 시 회원 찾는 메서드 명확하게 수정
=> fix: 카카오 회원의 탈퇴 후, 로그인 시 로직 처리 추가

.github/workflows/backend-ci-workflow.yml, backend/src/main/java/edonymyeon/backend/cache/application/HotPostsRedisRepository.java, backend/src/main/java/edonymyeon/backend/cache/application/PostCachingService.java, backend/src/main/java/edonymyeon/backend/cache/domain/CachedHotPost.java, backend/src/test/java/edonymyeon/backend/post/application/PostServiceHotPostsTest.java
- close: #359 
핫 게시글이 없다면 레디스에 빈 리스트가 저장 되는데, 빈 리스트 대신 null 로 저장됩니다
이로 인해 핫 게시글 조회에서 NPE 이 발생하는 것을 확인했습니다.
때문에 CachedHotPost 도메인에서 캐시를 refresh 하거나, get할때 null처리를 추가해주었습니다.
=> Fix/#359 캐싱된 핫게시글이 없을떄 npe 오류 해결

backend/src/main/java/edonymyeon/backend/comment/application/CommentService.java
- close: #381 
안드로이드에서 댓글 작성 시 이미지가 없을 경우, 이미지 값을 null로 보내는데, 이를 처리하였습니다.
=> fix: 댓글 작성 요청에서 이미지 값이 null로 들어오는 경우 처리

android/app/src/main/java/com/app/edonymyeon/data/service/client/RetrofitClient.kt, android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/mypage/MyPageFragment.kt, android/app/src/main/java/com/app/edonymyeon/presentation/ui/posteditor/PostEditorActivity.kt, android/app/src/main/res/values/strings.xml
- close: #368 
회원 정보 수정을 누르면 `준비 중인 기능입니다` 라는 안내 스낵바가 표시됩니다.
또한, 로그인을 하지 않으면 하단 `ConstraintLayout`이 보이지 않도록 구현하였고, 관련 로직들을 함수로 분리하였습니다.
위 요약 내용과 동일합니다..
> 15분..? 이해하는 데에 어려움 없이 보실 수 있을 것 같아요 ~
=> Fix/#368 회원정보수정 준비중

backend/src/main/java/edonymyeon/backend/comment/domain/Comment.java, backend/src/main/resources/db/migration/mysql/V1.2.1__change_comment_longtext.sql, backend/src/test/java/edonymyeon/backend/comment/integration/CommentIntegrationTest.java
- close: #386 
구글의 기다란 url은 댓글을 달 수 없는 이슈가 있어서,
댓글이 db에 저장될때 longtext로 저장되도록 수정하였습니다.
*현재 PR중에 여우의 알림PR, 그리고 추후에 구현되어야 하는 케로의 댓글 신고기능에서 Flyway가 적용되어야 하는데, merge 순서에 따른 flyway 파일의 버전 관리에 유의해야합니다.
=> fix: 댓글 글자수 제한을 게시글 글자수 제한과 동일하도록 수정

backend/src/main/java/edonymyeon/backend/comment/repository/CommentRepository.java, backend/src/main/java/edonymyeon/backend/image/commentimage/repository/CommentImageInfoRepository.java, backend/src/main/java/edonymyeon/backend/post/application/PostService.java
- close: #416 
post가 delete true된 상태에서 commentRepositoryByPostId를 하면 조회 결과가 무조건 없는 것을 알게되었습니다.
따라서 post를 delete true하는 동작을 PostService의 게시글 삭제 로직의 제일 뒤로 빼고, commentRepository의 @Modifying의 옵션을 수정했습니다. (삭제할때만 사용하는 것이라 괜찮을 것이라 판단)
추후 더 좋은 대안이 생각나면 리팩터링하도록 하겠습니다.
=> fix: 게시글 삭제시 댓글의 이미지가 deleted 컬럼이 true로 바뀌지 않던 이슈 수정

android/app/src/main/java/com/app/edonymyeon/data/common/CustomThrowableUtils.kt, android/app/src/main/java/com/app/edonymyeon/data/repository/AuthRepositoryImpl.kt, android/app/src/main/java/com/app/edonymyeon/data/repository/PostRepositoryImpl.kt, android/app/src/main/java/com/app/edonymyeon/presentation/ui/post/PostActivity.kt, android/app/src/main/java/com/app/edonymyeon/presentation/ui/postdetail/PostDetailActivity.kt, android/app/src/main/java/com/app/edonymyeon/presentation/ui/postdetail/PostDetailViewModel.kt, android/app/src/main/java/com/app/edonymyeon/presentation/ui/postdetail/dialog/PostDeletedDialog.kt, android/app/src/main/res/layout/activity_post.xml, android/app/src/main/res/layout/activity_post_detail.xml, android/app/src/main/res/layout/dialog_post_deleted.xml, android/app/src/main/res/layout/item_comment.xml, android/app/src/main/res/values/strings.xml
- close: #423 
삭제된 게시글을 클릭시 무한로딩 되지 않도록 수정하였습니다.
삭제된 게시글 클릭 시 무한로딩 되지 않고 '삭제된 게시글입니다.'라고 Dialog 뜰 수 있도록 하였습니다.
수정하는 김에 에러 코드에 대한 처리 하는 부분을 공통함수로 빼서 서버에서 전달하는 에러코드와 메시지를 CustomThrowable로 관리할 수 있도록 하였습니다!!
전체 게시물 refreshlayout 적용했고 게시글 상세에 제목 길이가 길어지는 경우에 잘리는 문제를 수정하였습니다. 
PostDetail에 상태가 점점 많아지면서 UiState로 리팩토링의 필요성을 느끼게 되네요😂
=> Fix/#423 삭제된게시글 무한로딩

android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/home/adapter/AllPostAdapter.kt, android/app/src/main/res/layout/fragment_home.xml
- close: #421
스크롤뷰안에 리사이클러뷰가 있어 이중 스크롤이 발생하는 문제 해결
=> refactor: 이중 스크롤 막기

backend/build.gradle, backend/src/docs/asciidoc/common/report-api.adoc, backend/src/docs/asciidoc/index.adoc
- close: #376 
테스트 실행 후 생기는 문서를 복사하는 작업(copyDocument)의 순서와 복제 위치(build 폴더 안)가 변경되었습니다~
build.gralde이 수정된 작업이라 한번씩 확인해주세욥~
로컬에서 ./gradlew clean build 실행하시고
build/libs 디렉토리의 jar 파일을 실행해보셔도 좋아요~
아래는 젠킨스를 통해 빌드할때 콘솔에 출력된 내용임니당
boot jar, jar -> test -> copyDocument -> build
test -> copyDocument -> boot jar, jar, build
=> Fix/#376 배포 이전 버전의 restdocs 문서가 조회되는 이슈 수정

backend/src/main/java/edonymyeon/backend/auth/application/AuthService.java, backend/src/test/java/edonymyeon/backend/auth/application/AuthServiceTest.java
- close: #459 
제곧내입니다.
일반 로그인과 소셜 로그인 매서드가 따로인 것이 개인적으로 맘에 안 듭니다 🥹
통일할 수 있으면 좋겠습니다
=> fix: 소셜로 회원가입 시에도 설정 초기화 작업을 수행하도록 변경

backend/src/main/java/edonymyeon/backend/auth/application/AuthService.java, backend/src/main/java/edonymyeon/backend/member/application/DeviceRepository.java, backend/src/main/java/edonymyeon/backend/member/repository/MemberRepository.java, backend/src/main/java/edonymyeon/backend/setting/application/SettingService.java, backend/src/main/java/edonymyeon/backend/setting/domain/Setting.java, backend/src/main/java/edonymyeon/backend/setting/repository/SettingCustomRepository.java, backend/src/main/java/edonymyeon/backend/setting/repository/SettingRepository.java, backend/src/main/java/edonymyeon/backend/setting/repository/SettingRepositoryImpl.java, backend/src/main/resources/application-prod-test.properties, backend/src/main/resources/application-prod.properties, backend/src/main/resources/db/migration/mysql/V1.3.4__add_device_token_index.sql
- close: #470 
호이가 작성해준 [회원가입 API 쿼리 정리 문서](https://www.notion.so/e33495efa9c74a5cbcb6b1dfe9259ca3?pvs=4)에서 보이는 성능 병목점을 완화했습니다.
(회원가입 1,500건 기준 156.27초 -> 33.47초)
+ 인덱스 적용 후 더 빨라졌습니다! (위와 다른 조건의 20,000건 기준 158초 ->  31.5초)
기존 쿼리에서 보이는 문제점은 크게 3가지였습니다.
1. Member 저장보다 Setting 저장을 먼저 한다.
그래서 Setting을 저장할 때 member_id를 null로 저장한 후,
Member가 저장되고 나면 Setting의 member_id 값을 변경하는 update 쿼리를 추가로 보낸다.
```SQL
insert into 
setting (is_active,member_id,setting_type) 
values 
(false,NULL,'NOTIFICATION_PER_COMMENT');
```
-> 
회원 저장
->
```SQL
update 
setting 
set 
is_active=false,member_id=2,setting_type='NOTIFICATION_PER_COMMENT' 
where 
id=8;
```
2. 회원 한 사람이 활성화/비활성화할 수 있는 Setting 항목이 N개라고 할 때,
회원 하나를 저장한 후 회원에 대한 각 Setting을 저장하는 쿼리가 N개 나간다. (N+1 INSERT)
3. Setting과 연관관계를 가지고 있는 Member의 정보를 이용하는 과정에서 발생하는 …
=> #470 회원가입 쿼리 개선

android/app/build.gradle.kts, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/app/edonymyeon/data/datasource/auth/AuthRemoteDataSource.kt, android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/mypage/MyPageFragment.kt, android/app/src/main/java/com/app/edonymyeon/presentation/ui/posteditor/adapter/PostEditorImagesAdapter.kt, android/app/src/main/java/com/app/edonymyeon/presentation/ui/profileupdate/ProfileUpdateActivity.kt, android/app/src/main/java/com/app/edonymyeon/presentation/ui/profileupdate/ProfileUpdateViewModel.kt, android/app/src/main/res/drawable/bg_666666_radius_6dp.xml, android/app/src/main/res/layout/activity_profile_update.xml, android/app/src/main/res/layout/activity_sign_up.xml, android/app/src/main/res/values/strings.xml
- close: #468 
회원정보수정 뷰 구현
회원정보수정 뷰를 구현했습니다.
또한 기존 회원정보가 뷰에 보이도록 했어요.
연휴동안 api까지 해서 올리려고 했는데, 아직 api 배포가 되지 않아서 이 부분은 추후 실제 잘 되는지까지 확인해서 올릴게요.
우선 뷰 먼저 리뷰 요청 보냅니다!
> 뷰,,라서 오래 걸릴 것 같진 않습니다..!  api 배포 전까지 머지되면 좋겠네요 😆 
사진 선택 부분은 `PickVisualMedia`를 이용했습니다.
- 갤러리 관련하여 별도의 권한을 요구하지 않는다는 장점이 있고,
- SDK 버전이 30 미만이거나, SDK Extensions의 버전이 2미만일 경우에는 ACTION_OPEN_DOCUMENT가 자동으로 실행되므로 버전 문제도 없을 것으로 보여요.
- 프로필 사진 선택이라 딱 한 장만 빠르게 쉭쉭 고를 수 있어 좋은 것 같구요.
ref.
https://developer.android.com/training/data-storage/shared/photopicker?hl=ko 
https://developer.android.com/reference/kotlin/androidx/activity/result/contract/ActivityResultContracts.PickVisualMedia 
여러분의 의견은 어떠신가요?
=> Feat/#468 회원정보수정 뷰 구현

android/app/build.gradle.kts, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/app/edonymyeon/presentation/ui/posteditor/PostEditorActivity.kt, android/app/src/main/res/xml/file_paths.xml
- close: #469 
사진을 촬영하여 올릴 시에 화질 저하 문제 개선
이전에는 사진 촬영 시에 TakePicturePreview를 사용해서 사진의 썸네일 이미지를 Bitmap으로 얻어와 화질이 낮았던 문제가 생겼고 이를 개선함
화질을 개선하는 방법이 카메라로 사진을 찍어서 그 사진을 저장한 후 uri를 통해 가져오는 방법 밖에 없는 것 같아서 그렇게 진행하였습니다! 
혹시  다른 좋은 방법이 있다면 알려주시면 감사하겠습니다😄 
Provider를 사용하여서 앱의 내부 캐시 저장소에 이미지를 임시 저장하도록 하고 갤러리에는 저장되지 않도록 하였습니다. 
캐시 저장소에 파일을 생성해서 이미지를 넣고 uri를 가져와서 launcher로 전달하기 위해서는 uri를 var 변수로 만들어야 했는데 혹시 더 좋은 방법이 있거나 리팩토링 해야할 부분이 있다면 알려주세요😊
그리고 카메라로 찍은 이미지가 회전하는 부분은 다른 pr에 넣어놔서 카메라 사진을 찍으면 회전이 되어서 나올겁니당😂
카메라 화질이 좋아졌는지도 확인 부탁드려요! 
애뮬레이터에서는 카메라를 찍어서 화질을 확인하는게 어려워서 갤럭시 노트 10+에서 확인했을 때는 화질이 좋았는데
다른 기기들도 확인해봐야할 것 같아여~!!
=> Refactor/#469 화질저하 리팩토링

android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/app/edonymyeon/presentation/ui/main/search/SearchFragment.kt, android/app/src/main/java/com/app/edonymyeon/presentation/ui/mypost/MyPostActivity.kt, android/app/src/main/res/layout/activity_my_post.xml, android/app/src/main/res/layout/fragment_search.xml, android/app/src/main/res/values/strings.xml
- close: #485 
화면이 비어 있는 경우 문구 추가
내가 쓴 글 화면과 검색 화면에서 비어있는 경우 해당 화면과 맞는 문구 보여주도록 구현
5분도 안 걸릴 간단한 이슈입니다!! 오류가 있는 봐주시면 감사하겠습니다😊
=> Feat/#485 빈화면문구추가
